### ISSUE TITLE
add "--preview" parameter to show the split N ways

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-split#12]

**Comment by tommy-anderson** [comment]
This would be a great addition, I would gladly take on the challenge. Any ideas on what I should start looking into to make this a possibility?

As I understand the problem is to get cypress to stop after a `cypress run` but still somehow get a 0 response, since we wouldn't want this to fail in CI for whatever reason.

**Comment by bahmutov** [comment]
@tommy-anderson thanks - it was a lot of refactoring, so I did it myself, but you can find the code in https://github.com/bahmutov/cypress-split/pull/196
